Docker
dorksquad/artwork pull request #15
Opened 2021-07-16 16:56 UTC by JordanCaseCode

Adding docker compose to stand up service and mongo separately 

Fixes #14

2021-07-18 00:07 UTC, cgrountree requested changes
when running `mvn clean isntall` im seeing the following warning:

```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.dorksquad:artwork:jar:0.0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.version' for org.jetbrains:annotations:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 67, column 22
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
```

not sure how soon this will be deprecated :thinking: 


i'm also seeing the following log right before the tests finishing running:

```
2021-07-17 18:01:01.390  INFO 8511 --- [localhost:49157] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:49157

com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:112) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:648) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:356) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.InternalStreamConnection.receive(InternalStreamConnection.java:316) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:215) ~[mongodb-driver-core-4.1.2.jar:na]
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) ~[mongodb-driver-core-4.1.2.jar:na]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```
the tests pass, but im not sure if this is expected or not

2021-07-18 00:07 UTC, cgrountree commented on Dockerfile
> +
can you remove the extra line here 😂

2021-07-18 00:07 UTC, cgrountree commented on Dockerfile
> +
same as above

2021-07-19 18:25 UTC, JordanCaseCode commented on Dockerfile
> +
no

2021-07-19 18:25 UTC, JordanCaseCode commented on Dockerfile
> +
never

2021-07-19 18:28 UTC, JordanCaseCode commented
> when running `mvn clean isntall` im seeing the following warning:
> 
> ```
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.dorksquad:artwork:jar:0.0.1-SNAPSHOT
> [WARNING] 'dependencies.dependency.version' for org.jetbrains:annotations:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 67, column 22
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> ```
> 
> not sure how soon this will be deprecated 
> 
> i'm also seeing the following log right before the tests finishing running:
> 
> ```
> 2021-07-17 18:01:01.390  INFO 8511 --- [localhost:49157] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:49157
> 
> com.mongodb.MongoSocketReadException: Prematurely reached end of stream
> 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:112) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:648) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:356) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receive(InternalStreamConnection.java:316) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:215) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
> ```
> 
> the tests pass, but im not sure if this is expected or not



> when running `mvn clean isntall` im seeing the following warning:
> 
> ```
> [WARNING]
> [WARNING] Some problems were encountered while building the effective model for com.dorksquad:artwork:jar:0.0.1-SNAPSHOT
> [WARNING] 'dependencies.dependency.version' for org.jetbrains:annotations:jar is either LATEST or RELEASE (both of them are being deprecated) @ line 67, column 22
> [WARNING]
> [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
> [WARNING]
> [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
> [WARNING]
> ```
> 
> not sure how soon this will be deprecated 
> 
> i'm also seeing the following log right before the tests finishing running:
> 
> ```
> 2021-07-17 18:01:01.390  INFO 8511 --- [localhost:49157] org.mongodb.driver.cluster               : Exception in monitor thread while connecting to server localhost:49157
> 
> com.mongodb.MongoSocketReadException: Prematurely reached end of stream
> 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:112) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.SocketStream.read(SocketStream.java:131) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:648) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveMessageWithAdditionalTimeout(InternalStreamConnection.java:513) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:356) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.InternalStreamConnection.receive(InternalStreamConnection.java:316) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:215) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144) ~[mongodb-driver-core-4.1.2.jar:na]
> 	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
> ```
> 
> the tests pass, but im not sure if this is expected or not

Both are resolved.
1 - jetbrains version just needed to be set to a non-dynamic version (16.0.1 instead of RELEASE)
2 - I removed the closing of the mongodb docker container at the end of the test class. This is handled with autoCloseable. So it was basically just a harsh closing of the container while the testcontainer was still trying to handle it.

2021-07-21 00:38 UTC, cgrountree commented
was able to confirm with this branch https://github.com/dorksquad/artwork/pull/19 that insertion into mongo via the addArtworks endpoint is successful before the addition of docker compose.

so we probably just need to continue trying to find how to get logging for the containers to track down exactly why the insertion doesn't happen here.

2021-07-24 04:10 UTC, cgrountree approved these changes
:boom:

2021-07-24 04:11 UTC, merged